apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arrienda-back
  namespace: back
spec:
   ingressClassName: public
   rules:
   - host: 
     http:
       paths:
       - path: /api
         pathType: Prefix
         backend:
           service:
             name: arrienda-back
             port:
               number: 8080